const axios = require('axios');

let handler = async (m, { command, text, Bellah }) => {
  if (!text || !text.includes('|')) {
    return m.reply(`✳️ Invalid format.\n\nExample: *.${command} Gifted|Dave*`);
  }

  let [text1, text2] = text.split('|').map(t => t.trim());
  if (!text1 || !text2) return m.reply('❌ Please provide two valid texts separated by "|".');

  try {
    const apiUrl = `https://apikey.sazxofficial.web.id/api/imagecreator/pornhub?text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}`;
    const res = await fetch(apiUrl);
    const json = await res.json();

    if (!json.status) return m.reply('⚠️ Sorry, the API is currently down.');

    await Bellah.sendMessage(m.chat, {
      image: { url: json.result },
      caption: `✅ *Logo Created Successfully!*\n\n➤ *Text1:* ${text1}\n➤ *Text2:* ${text2}`,
      contextInfo: {
        externalAdReply: {
          title: "PH Style Logo Generator",
          body: "Generated by 𝐃𝐀𝐕𝐄-𝐗𝐌𝐃",
          thumbnailUrl: json.result,
          mediaType: 1,
          renderLargerThumbnail: true,
          sourceUrl: json.result
        }
      }
    }, { quoted: m });

  } catch (e) {
    console.error(e);
    m.reply('❌ An error occurred while generating the logo.');
  }
};

handler.help = ['phlogo'];
handler.tags = ['logo'];
handler.command = ['phlogo'];

module.exports = handler;
